name: polaris_client
version: 1.0.0
description: Client library for Polaris geocoding service
homepage: homepage
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  http: ^0.13.3
dev_dependencies:
  test: ^1.3.0
